ALTER TABLE gold.fraud_prediction
    ADD COLUMN IF NOT EXISTS explanation TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS explanation_type VARCHAR(32) NOT NULL DEFAULT 'DETERMINISTIC',
    ADD COLUMN IF NOT EXISTS explanation_model VARCHAR(120);
